import { MetadataRoute } from 'next'

export default function sitemap(): MetadataRoute.Sitemap {
  const base = 'https://keyword-mixer.vercel.app'
  const now = new Date()

  return [

    // 가이드 페이지 (구글 크롤 품질 향상)
    { url: `${base}/guide`, lastModified: now, changeFrequency: 'weekly' as const, priority: 0.85 },
    { url: `${base}/guide/severance-pay-guide`, lastModified: now, changeFrequency: 'monthly' as const, priority: 0.82 },
    { url: `${base}/guide/bmi-guide`, lastModified: now, changeFrequency: 'monthly' as const, priority: 0.82 },
    { url: `${base}/guide/vat-guide`, lastModified: now, changeFrequency: 'monthly' as const, priority: 0.82 },
    { url: `${base}/guide/tax-refund-guide`, lastModified: now, changeFrequency: 'monthly' as const, priority: 0.82 },
    { url: `${base}/guide/mortgage-guide`, lastModified: now, changeFrequency: 'monthly' as const, priority: 0.82 },
    { url: `${base}/guide/minimum-wage-guide`, lastModified: now, changeFrequency: 'monthly' as const, priority: 0.82 },
    { url: `${base}/guide/date-calculator-guide`, lastModified: now, changeFrequency: 'monthly' as const, priority: 0.80 },
    { url: `${base}/guide/health-insurance-guide`, lastModified: now, changeFrequency: 'monthly' as const, priority: 0.80 },
    // 홈페이지
    {
      url: base,
      lastModified: now,
      changeFrequency: 'daily' as const,
      priority: 1.0,
    },
    {
      url: `${base}/bmi-calculator-pro`,
      lastModified: now,
      changeFrequency: 'weekly' as const,
      priority: 0.95,
    },
    {
      url: `${base}/severance-pay`,
      lastModified: now,
      changeFrequency: 'weekly' as const,
      priority: 0.95,
    },
    {
      url: `${base}/vat-calculator`,
      lastModified: now,
      changeFrequency: 'weekly' as const,
      priority: 0.95,
    },
    {
      url: `${base}/tax-refund`,
      lastModified: now,
      changeFrequency: 'weekly' as const,
      priority: 0.95,
    },
    {
      url: `${base}/mortgage-calculator`,
      lastModified: now,
      changeFrequency: 'weekly' as const,
      priority: 0.95,
    },
    {
      url: `${base}/minimum-wage`,
      lastModified: now,
      changeFrequency: 'weekly' as const,
      priority: 0.95,
    },
    {
      url: `${base}/lease-calculator`,
      lastModified: now,
      changeFrequency: 'weekly' as const,
      priority: 0.95,
    },
    {
      url: `${base}/childbirth-subsidy`,
      lastModified: now,
      changeFrequency: 'weekly' as const,
      priority: 0.95,
    },
    {
      url: `${base}/investment-return`,
      lastModified: now,
      changeFrequency: 'weekly' as const,
      priority: 0.9,
    },
    {
      url: `${base}/gpa-calculator`,
      lastModified: now,
      changeFrequency: 'weekly' as const,
      priority: 0.9,
    },
    {
      url: `${base}/stamp-maker`,
      lastModified: now,
      changeFrequency: 'weekly' as const,
      priority: 0.9,
    },
    {
      url: `${base}/pomodoro-pro`,
      lastModified: now,
      changeFrequency: 'weekly' as const,
      priority: 0.9,
    },
    {
      url: `${base}/stopwatch`,
      lastModified: now,
      changeFrequency: 'weekly' as const,
      priority: 0.9,
    },
    {
      url: `${base}/password-strength`,
      lastModified: now,
      changeFrequency: 'weekly' as const,
      priority: 0.9,
    },
    {
      url: `${base}/alcohol-calculator`,
      lastModified: now,
      changeFrequency: 'weekly' as const,
      priority: 0.9,
    },
    {
      url: `${base}/zodiac-calculator`,
      lastModified: now,
      changeFrequency: 'weekly' as const,
      priority: 0.9,
    },
    {
      url: `${base}/love-calculator`,
      lastModified: now,
      changeFrequency: 'weekly' as const,
      priority: 0.9,
    },
    {
      url: `${base}/mbti-compatibility`,
      lastModified: now,
      changeFrequency: 'weekly' as const,
      priority: 0.9,
    },
    {
      url: `${base}/biorhythm`,
      lastModified: now,
      changeFrequency: 'weekly' as const,
      priority: 0.88,
    },
    {
      url: `${base}/lucky-number`,
      lastModified: now,
      changeFrequency: 'weekly' as const,
      priority: 0.88,
    },
    {
      url: `${base}/ideal-weight`,
      lastModified: now,
      changeFrequency: 'weekly' as const,
      priority: 0.8,
    },
    {
      url: `${base}/water-intake`,
      lastModified: now,
      changeFrequency: 'weekly' as const,
      priority: 0.8,
    },
    {
      url: `${base}/calories-burned-swim`,
      lastModified: now,
      changeFrequency: 'weekly' as const,
      priority: 0.8,
    },
    {
      url: `${base}/protein-calculator`,
      lastModified: now,
      changeFrequency: 'weekly' as const,
      priority: 0.8,
    },
    {
      url: `${base}/waist-hip-ratio`,
      lastModified: now,
      changeFrequency: 'weekly' as const,
      priority: 0.8,
    },
    {
      url: `${base}/health-insurance`,
      lastModified: now,
      changeFrequency: 'weekly' as const,
      priority: 0.8,
    },
    {
      url: `${base}/loan-comparison`,
      lastModified: now,
      changeFrequency: 'weekly' as const,
      priority: 0.8,
    },
    {
      url: `${base}/date-diff-calculator`,
      lastModified: now,
      changeFrequency: 'weekly' as const,
      priority: 0.8,
    },
    {
      url: `${base}/unit-price-calculator`,
      lastModified: now,
      changeFrequency: 'weekly' as const,
      priority: 0.8,
    },
    {
      url: `${base}/reading-speed`,
      lastModified: now,
      changeFrequency: 'weekly' as const,
      priority: 0.8,
    },
    {
      url: `${base}/paint-calculator`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.78,
    },
    {
      url: `${base}/concrete-calculator`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.78,
    },
    {
      url: `${base}/retirement-calculator`,
      lastModified: now,
      changeFrequency: 'weekly' as const,
      priority: 0.8,
    },
    {
      url: `${base}/real-estate-tax`,
      lastModified: now,
      changeFrequency: 'weekly' as const,
      priority: 0.8,
    },
    {
      url: `${base}/freelancer-tax`,
      lastModified: now,
      changeFrequency: 'weekly' as const,
      priority: 0.8,
    },
    {
      url: `${base}/split-calculator`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.78,
    },
    {
      url: `${base}/fuel-cost`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.78,
    },
    {
      url: `${base}/meeting-cost`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.78,
    },
    {
      url: `${base}/number-base-converter`,
      lastModified: now,
      changeFrequency: 'weekly' as const,
      priority: 0.8,
    },
    {
      url: `${base}/file-size-converter`,
      lastModified: now,
      changeFrequency: 'weekly' as const,
      priority: 0.8,
    },
    {
      url: `${base}/scientific-calculator`,
      lastModified: now,
      changeFrequency: 'weekly' as const,
      priority: 0.82,
    },
    {
      url: `${base}/timezone-meeting`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.78,
    },
    {
      url: `${base}/nutrition-score`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.78,
    },
    {
      url: `${base}/invoice-calculator`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.78,
    },
    {
      url: `${base}/salary-calculator`,
      lastModified: now,
      changeFrequency: 'weekly' as const,
      priority: 0.8,
    },
    {
      url: `${base}/compound-interest`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.78,
    },
    {
      url: `${base}/loan-repayment-table`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.78,
    },
    {
      url: `${base}/statistics-calculator`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.75,
    },
    {
      url: `${base}/savings-calculator`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.75,
    },
    {
      url: `${base}/jeonse-calculator`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.78,
    },
    {
      url: `${base}/name-meaning`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.78,
    },
    {
      url: `${base}/lunch-picker`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.75,
    },
    {
      url: `${base}/text-cleaner`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.75,
    },
    {
      url: `${base}/age-calculator`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.7,
    },
    {
      url: `${base}/ascii-art`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.65,
    },
    {
      url: `${base}/aspect-ratio`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.65,
    },
    {
      url: `${base}/baby-development`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.68,
    },
    {
      url: `${base}/base64`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.65,
    },
    {
      url: `${base}/binary-text`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.65,
    },
    {
      url: `${base}/blood-pressure-tracker`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.68,
    },
    {
      url: `${base}/blood-sugar-tracker`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.68,
    },
    {
      url: `${base}/body-fat-calculator`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.68,
    },
    {
      url: `${base}/calculators`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.7,
    },
    {
      url: `${base}/calorie-food-search`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.68,
    },
    {
      url: `${base}/car-cost-calculator`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.68,
    },
    {
      url: `${base}/char-counter`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.7,
    },
    {
      url: `${base}/character-counter-pro`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.7,
    },
    {
      url: `${base}/color-contrast`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.65,
    },
    {
      url: `${base}/color-converter`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.65,
    },
    {
      url: `${base}/color-extractor`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.65,
    },
    {
      url: `${base}/color-palette`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.65,
    },
    {
      url: `${base}/color-temperature`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.65,
    },
    {
      url: `${base}/countdown-creator`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.65,
    },
    {
      url: `${base}/cron-generator`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.65,
    },
    {
      url: `${base}/css-gradient`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.65,
    },
    {
      url: `${base}/css-unit-converter`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.65,
    },
    {
      url: `${base}/currency-premium`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.68,
    },
    {
      url: `${base}/date-calculator`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.7,
    },
    {
      url: `${base}/dday-calculator`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.7,
    },
    {
      url: `${base}/electricity-calculator`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.68,
    },
    {
      url: `${base}/emoji-search`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.68,
    },
    {
      url: `${base}/exchange-rate`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.7,
    },
    {
      url: `${base}/exercise-calorie`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.68,
    },
    {
      url: `${base}/gas-calculator`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.65,
    },
    {
      url: `${base}/hanja-converter`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.65,
    },
    {
      url: `${base}/hash-generator`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.65,
    },
    {
      url: `${base}/hashtag-generator`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.7,
    },
    {
      url: `${base}/height-predictor`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.65,
    },
    {
      url: `${base}/id-generator`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.65,
    },
    {
      url: `${base}/image-base64`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.65,
    },
    {
      url: `${base}/image-compressor`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.65,
    },
    {
      url: `${base}/image-editor`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.65,
    },
    {
      url: `${base}/interest-calculator`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.68,
    },
    {
      url: `${base}/internet-speed-converter`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.65,
    },
    {
      url: `${base}/invoice-generator`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.68,
    },
    {
      url: `${base}/ip-lookup`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.65,
    },
    {
      url: `${base}/json-csv`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.65,
    },
    {
      url: `${base}/json-formatter`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.65,
    },
    {
      url: `${base}/json-to-typescript`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.65,
    },
    {
      url: `${base}/json-validator`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.65,
    },
    {
      url: `${base}/jwt-decoder`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.65,
    },
    {
      url: `${base}/keyword-combiner`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.7,
    },
    {
      url: `${base}/keyword-generator`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.7,
    },
    {
      url: `${base}/line-break-remover`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.65,
    },
    {
      url: `${base}/lotto`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.68,
    },
    {
      url: `${base}/markdown-editor`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.65,
    },
    {
      url: `${base}/menstrual-calculator`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.68,
    },
    {
      url: `${base}/meta-tag-generator`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.65,
    },
    {
      url: `${base}/morse-code`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.65,
    },
    {
      url: `${base}/nickname-generator`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.65,
    },
    {
      url: `${base}/number-converter`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.65,
    },
    {
      url: `${base}/number-to-korean`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.65,
    },
    {
      url: `${base}/nutrition-calculator`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.68,
    },
    {
      url: `${base}/password-generator`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.7,
    },
    {
      url: `${base}/payslip-generator`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.68,
    },
    {
      url: `${base}/pdf-tools`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.65,
    },
    {
      url: `${base}/percentage-calculator`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.68,
    },
    {
      url: `${base}/pyeongsu-calculator`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.68,
    },
    {
      url: `${base}/qr-generator`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.68,
    },
    {
      url: `${base}/random-picker`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.65,
    },
    {
      url: `${base}/regex-tester`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.65,
    },
    {
      url: `${base}/roman-numeral`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.65,
    },
    {
      url: `${base}/sleep-calculator`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.68,
    },
    {
      url: `${base}/speed-distance-time`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.68,
    },
    {
      url: `${base}/spell-checker`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.68,
    },
    {
      url: `${base}/steps-calorie`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.65,
    },
    {
      url: `${base}/stock-calculator`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.68,
    },
    {
      url: `${base}/subscription-calculator`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.65,
    },
    {
      url: `${base}/tax-calculator`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.68,
    },
    {
      url: `${base}/text-diff`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.65,
    },
    {
      url: `${base}/text-to-table`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.65,
    },
    {
      url: `${base}/text-tools`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.65,
    },
    {
      url: `${base}/time-calculator`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.68,
    },
    {
      url: `${base}/timer`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.68,
    },
    {
      url: `${base}/timezone-converter`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.65,
    },
    {
      url: `${base}/tip-calculator`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.65,
    },
    {
      url: `${base}/typing-speed`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.65,
    },
    {
      url: `${base}/unit-converter`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.68,
    },
    {
      url: `${base}/url-encoder`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.65,
    },
    {
      url: `${base}/utm-builder`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.7,
    },
    {
      url: `${base}/uuid-generator`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.65,
    },
    {
      url: `${base}/word-frequency`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.65,
    },
    {
      url: `${base}/world-clock`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.65,
    },
    {
      url: `${base}/youtube-tags`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.7,
    },
  ]
}
// NOTE: about/privacy/terms/contact pages added
