'use client'
import { useState } from 'react'
import { Copy, CheckCheck } from 'lucide-react'
import { useLang } from './LangContext'
import ToolFooter from './ToolFooter'

const T = {
  ko: { title: 'SEO 메타태그 생성기', desc: 'HTML 메타태그, Open Graph, Twitter Card를 즉시 생성. SEO 점수 분석 포함.' },
  en: { title: 'SEO Meta Tag Generator', desc: 'Generate HTML meta tags, Open Graph, and Twitter Cards instantly with SEO score analysis.' }
}

export default function MetaTagGenerator() {
  const { lang } = useLang()
  const tx = T[lang]
  const [form, setForm] = useState({ title: '', desc: '', keywords: '', url: '', image: '', author: '', locale: 'ko_KR', type: 'website', twitterCard: 'summary_large_image', robots: 'index, follow', canonical: '' })
  const [copied, setCopied] = useState<string|null>(null)

  const set = (k: string, v: string) => setForm(p => ({ ...p, [k]: v }))
  const copy = async (text: string, key: string) => { await navigator.clipboard.writeText(text); setCopied(key); setTimeout(() => setCopied(null), 1500) }

  const titleLen = form.title.length
  const descLen = form.desc.length
  const titleScore = titleLen >= 30 && titleLen <= 60 ? 100 : titleLen > 0 ? 50 : 0
  const descScore = descLen >= 120 && descLen <= 160 ? 100 : descLen > 0 ? 50 : 0
  const seoScore = Math.round((titleScore + descScore + (form.keywords ? 80 : 0) + (form.url ? 100 : 0) + (form.image ? 80 : 0)) / 5)

  const metaTags = `<!-- SEO Meta Tags - Generated by Keyword Mixer -->
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
${form.title ? `<title>${form.title}</title>\n<meta name="title" content="${form.title}">` : ''}
${form.desc ? `<meta name="description" content="${form.desc}">` : ''}
${form.keywords ? `<meta name="keywords" content="${form.keywords}">` : ''}
${form.author ? `<meta name="author" content="${form.author}">` : ''}
<meta name="robots" content="${form.robots}">
${form.canonical || form.url ? `<link rel="canonical" href="${form.canonical || form.url}">` : ''}

<!-- Open Graph -->
<meta property="og:type" content="${form.type}">
${form.title ? `<meta property="og:title" content="${form.title}">` : ''}
${form.desc ? `<meta property="og:description" content="${form.desc}">` : ''}
${form.url ? `<meta property="og:url" content="${form.url}">` : ''}
${form.image ? `<meta property="og:image" content="${form.image}">` : ''}
<meta property="og:locale" content="${form.locale}">

<!-- Twitter Card -->
<meta name="twitter:card" content="${form.twitterCard}">
${form.title ? `<meta name="twitter:title" content="${form.title}">` : ''}
${form.desc ? `<meta name="twitter:description" content="${form.desc}">` : ''}
${form.image ? `<meta name="twitter:image" content="${form.image}">` : ''}`

  const fields = [
    { key: 'title', label: lang==='ko'?'페이지 제목':'Page Title', placeholder: lang==='ko'?'30-60자 권장':'30-60 chars recommended', len: titleLen, max: 60, good: titleLen>=30&&titleLen<=60 },
    { key: 'desc', label: lang==='ko'?'메타 설명':'Meta Description', placeholder: lang==='ko'?'120-160자 권장':'120-160 chars recommended', len: descLen, max: 160, good: descLen>=120&&descLen<=160 },
    { key: 'keywords', label: lang==='ko'?'키워드':'Keywords', placeholder: lang==='ko'?'키워드1, 키워드2, ...':'keyword1, keyword2, ...', len: null, max: null, good: null },
    { key: 'url', label: 'URL', placeholder: 'https://example.com/page', len: null, max: null, good: null },
    { key: 'image', label: lang==='ko'?'OG 이미지 URL':'OG Image URL', placeholder: 'https://example.com/image.jpg', len: null, max: null, good: null },
    { key: 'author', label: lang==='ko'?'작성자':'Author', placeholder: lang==='ko'?'작성자 이름':'Author name', len: null, max: null, good: null },
    { key: 'canonical', label: lang==='ko'?'카노니컬 URL (선택)':'Canonical URL (optional)', placeholder: 'https://example.com/canonical', len: null, max: null, good: null },
  ]

  return (
    <div className="max-w-4xl mx-auto px-4 py-10">
      <div className="text-center mb-8">
        <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-brand-500/10 border border-brand-500/20 text-brand-400 text-xs font-mono mb-4">
          <span className="w-1.5 h-1.5 rounded-full bg-brand-400 animate-pulse" />Free SEO Tool
        </div>
        <h1 className="text-4xl font-extrabold text-white mb-3">{tx.title}</h1>
        <p className="text-slate-300 text-base max-w-xl mx-auto">{tx.desc}</p>
      </div>

      {/* SEO 점수 */}
      <div className="rounded-xl border border-surface-border bg-[#1a1d27] p-4 mb-5">
        <div className="flex items-center justify-between mb-2">
          <p className="text-sm font-medium text-slate-200">{lang==='ko'?'SEO 점수':'SEO Score'}</p>
          <span className={`text-2xl font-bold font-mono ${seoScore>=80?'text-brand-400':seoScore>=50?'text-yellow-400':'text-red-400'}`}>{seoScore}/100</span>
        </div>
        <div className="h-2 bg-surface-border rounded-full overflow-hidden">
          <div className={`h-full rounded-full transition-all ${seoScore>=80?'bg-brand-500':seoScore>=50?'bg-yellow-500':'bg-red-500'}`} style={{width:`${seoScore}%`}} />
        </div>
        <div className="flex gap-4 mt-2 text-xs">
          <span className={titleScore===100?'text-brand-400':titleScore>0?'text-yellow-400':'text-slate-600'}>
            {lang==='ko'?`제목 (${titleLen}자)`:`Title (${titleLen})`} {titleScore===100?'✓':titleLen>0?'△':'✗'}
          </span>
          <span className={descScore===100?'text-brand-400':descScore>0?'text-yellow-400':'text-slate-600'}>
            {lang==='ko'?`설명 (${descLen}자)`:`Desc (${descLen})`} {descScore===100?'✓':descLen>0?'△':'✗'}
          </span>
        </div>
      </div>

      <div className="grid md:grid-cols-2 gap-5 mb-5">
        {/* 입력 폼 */}
        <div className="rounded-xl border border-surface-border bg-[#1a1d27] p-4 flex flex-col gap-3">
          {fields.map(f => (
            <div key={f.key}>
              <div className="flex justify-between mb-1">
                <label className="text-xs text-slate-400 font-medium">{f.label}</label>
                {f.len !== null && <span className={`text-xs font-mono ${f.good?'text-brand-400':f.len>0?'text-yellow-400':'text-slate-600'}`}>{f.len}/{f.max}</span>}
              </div>
              {f.key === 'desc' ? (
                <textarea value={(form as any)[f.key]} onChange={e => set(f.key, e.target.value)} placeholder={f.placeholder} rows={3}
                  className="w-full bg-[#0f1117] border border-surface-border rounded-lg px-3 py-2 text-sm text-slate-200 placeholder-slate-600 focus:outline-none focus:border-brand-500/50 transition-all resize-none" />
              ) : (
                <input value={(form as any)[f.key]} onChange={e => set(f.key, e.target.value)} placeholder={f.placeholder}
                  className="w-full bg-[#0f1117] border border-surface-border rounded-lg px-3 py-2 text-sm text-slate-200 placeholder-slate-600 focus:outline-none focus:border-brand-500/50 transition-all" />
              )}
            </div>
          ))}
          <div className="grid grid-cols-2 gap-2">
            {[['locale', 'ko_KR', 'en_US', lang==='ko'?'언어':'Locale'], ['type', 'website', 'article', 'OG Type'], ['robots', 'index, follow', 'noindex, nofollow', 'Robots'], ['twitterCard', 'summary_large_image', 'summary', 'Twitter Card']].map(([k, v1, v2, label]) => (
              <div key={k}>
                <label className="text-xs text-slate-400 block mb-1">{label}</label>
                <select value={(form as any)[k]} onChange={e => set(k, e.target.value)}
                  className="w-full bg-[#0f1117] border border-surface-border rounded-lg px-2 py-1.5 text-xs text-slate-200 focus:outline-none focus:border-brand-500/50 transition-all">
                  <option value={v1}>{v1}</option>
                  <option value={v2}>{v2}</option>
                </select>
              </div>
            ))}
          </div>
        </div>

        {/* 결과 */}
        <div className="rounded-xl border border-surface-border bg-[#1a1d27] overflow-hidden">
          <div className="flex items-center justify-between px-4 py-2.5 border-b border-surface-border">
            <span className="text-sm font-medium text-slate-200">{lang==='ko'?'생성된 메타태그':'Generated Meta Tags'}</span>
            <button onClick={() => copy(metaTags, 'meta')} className={`text-xs px-3 py-1.5 rounded-lg border flex items-center gap-1 transition-all ${copied==='meta'?'bg-brand-500/20 border-brand-500/40 text-brand-400':'border-surface-border text-slate-300 hover:border-brand-500/40'}`}>
              {copied==='meta'?<CheckCheck size={12}/>:<Copy size={12}/>} {copied==='meta'?(lang==='ko'?'복사됨!':'Copied!'):(lang==='ko'?'전체 복사':'Copy All')}
            </button>
          </div>
          <pre className="px-4 py-3 text-xs text-slate-300 font-mono overflow-auto max-h-[500px] leading-relaxed whitespace-pre-wrap break-all bg-[#0f1117]">{metaTags}</pre>
        </div>
      </div>

      <ToolFooter
        toolName={lang==='ko'?'SEO 메타태그 생성기':'SEO Meta Tag Generator'}
        toolUrl="https://keyword-mixer.vercel.app/meta-tag-generator"
        description={tx.desc}
        howToUse={lang==='ko'?[
          {step:'기본 정보 입력', desc:'페이지 제목, 메타 설명, 키워드, URL을 입력하세요.'},
          {step:'SEO 점수 확인', desc:'상단 SEO 점수가 80점 이상이 되도록 내용을 최적화하세요.'},
          {step:'OG/Twitter 설정', desc:'소셜 미디어 공유 시 표시될 이미지와 타입을 설정하세요.'},
          {step:'코드 복사', desc:'전체 복사 버튼으로 생성된 메타태그를 HTML <head>에 붙여넣으세요.'},
        ]:[
          {step:'Enter basic info', desc:'Fill in page title, meta description, keywords, and URL.'},
          {step:'Check SEO score', desc:'Optimize content until SEO score reaches 80+.'},
          {step:'Set OG/Twitter', desc:'Configure image and type for social media sharing.'},
          {step:'Copy code', desc:'Copy all generated meta tags and paste into your HTML <head>.'},
        ]}
        whyUse={lang==='ko'?[
          {title:'SEO 점수 실시간 분석', desc:'제목·설명 길이를 실시간으로 분석해 최적 길이를 안내합니다.'},
          {title:'Open Graph 지원', desc:'카카오톡, Facebook 공유 시 미리보기가 표시되도록 OG 태그를 생성합니다.'},
          {title:'Twitter Card 지원', desc:'Twitter 공유 시 이미지와 함께 표시되는 카드 형태의 메타태그를 생성합니다.'},
          {title:'원클릭 복사', desc:'생성된 HTML 코드를 버튼 하나로 전체 복사할 수 있습니다.'},
        ]:[
          {title:'Real-time SEO analysis', desc:'Analyzes title and description length with optimization guidance.'},
          {title:'Open Graph support', desc:'Generates OG tags for rich previews on Facebook, KakaoTalk.'},
          {title:'Twitter Card support', desc:'Creates Twitter Card meta tags for image-rich tweet previews.'},
          {title:'One-click copy', desc:'Copy all generated HTML code with a single button click.'},
        ]}
        faqs={lang==='ko'?[
          {q:'메타태그가 SEO에 중요한 이유는?', a:'검색엔진이 페이지 내용을 이해하고 검색 결과에 표시할 제목·설명을 결정하는 데 사용됩니다. 클릭률(CTR)에 직접 영향을 줍니다.'},
          {q:'메타 키워드는 아직 유효한가요?', a:'구글은 meta keywords를 더 이상 순위 결정에 사용하지 않지만, 네이버 등 일부 검색엔진은 여전히 참고합니다.'},
          {q:'카노니컬 URL이란?', a:'중복 컨텐츠 문제를 해결하기 위해 대표 URL을 지정하는 태그입니다. www와 non-www, http/https 중복을 방지합니다.'},
          {q:'Open Graph 이미지 권장 크기는?', a:'1200x630px (1.91:1 비율)을 권장합니다. 최소 600x315px 이상이어야 합니다.'},
        ]:[
          {q:'Why are meta tags important for SEO?', a:'Search engines use meta tags to understand page content and determine titles/descriptions in search results, directly affecting CTR.'},
          {q:'Are meta keywords still useful?', a:'Google no longer uses meta keywords for ranking, but some search engines like Naver still reference them.'},
          {q:'What is a canonical URL?', a:'A canonical tag specifies the preferred URL to prevent duplicate content issues between www/non-www, http/https variations.'},
          {q:'What is the recommended OG image size?', a:'1200x630px (1.91:1 ratio) is recommended. Minimum 600x315px.'},
        ]}
        keywords="SEO 메타태그 · 메타태그 생성기 · Open Graph · Twitter Card · SEO 최적화 · 메타 디스크립션 · meta tag generator · SEO meta tags · Open Graph generator · Twitter card generator · HTML meta tags · SEO tool"
      />
    </div>
  )
}
