// lib/exportExcel.ts — Excel export with xlsx

export async function downloadExcel(keywords: string[], filename = 'keywords') {
  // Dynamic import so bundle stays small
  const XLSX = await import('xlsx')

  const ws = XLSX.utils.aoa_to_sheet([
    ['#', 'Keyword'],
    ...keywords.map((kw, i) => [i + 1, kw]),
  ])

  // Column widths
  ws['!cols'] = [{ wch: 6 }, { wch: 50 }]

  // Header style hint (not all renderers support this but xlsx handles it)
  const headerCells = ['A1', 'B1']
  for (const cell of headerCells) {
    if (ws[cell]) {
      ws[cell].s = {
        font: { bold: true, color: { rgb: 'FFFFFF' } },
        fill: { fgColor: { rgb: '16A34A' } },
        alignment: { horizontal: 'center' },
      }
    }
  }

  const wb = XLSX.utils.book_new()
  XLSX.utils.book_append_sheet(wb, ws, 'Keywords')

  // Add metadata sheet
  const meta = XLSX.utils.aoa_to_sheet([
    ['Generated by', 'Keyword Mixer (keywordmixer.app)'],
    ['Total Keywords', keywords.length],
    ['Date', new Date().toLocaleString('ko-KR')],
  ])
  XLSX.utils.book_append_sheet(wb, meta, 'Info')

  XLSX.writeFile(wb, `${filename}_${Date.now()}.xlsx`)
}

export function downloadCSV(keywords: string[], filename = 'keywords') {
  const header = 'No,Keyword\n'
  const rows = keywords.map((k, i) => `${i + 1},"${k.replace(/"/g, '""')}"`).join('\n')
  const blob = new Blob(['\uFEFF' + header + rows], { type: 'text/csv;charset=utf-8;' })
  triggerDownload(blob, `${filename}_${Date.now()}.csv`)
}

export function downloadTXT(keywords: string[], filename = 'keywords') {
  const blob = new Blob([keywords.join('\n')], { type: 'text/plain;charset=utf-8;' })
  triggerDownload(blob, `${filename}_${Date.now()}.txt`)
}

function triggerDownload(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}
